# Generated by Django 2.2.7 on 2019-11-05 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('map_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('can_edit', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('layer_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.TextField()),
                ('color', models.TextField()),
                ('map_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layer', to='core.Map')),
            ],
        ),
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('data_point_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.TextField()),
                ('size', models.IntegerField()),
                ('latitude', models.TextField()),
                ('longitude', models.TextField()),
                ('layer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_point', to='core.Layer')),
            ],
        ),
    ]
